import {
  Certificate,
  CertificateStatus,
  CertProfile,
  TestCase,
  TestStatus,
  ErrorCategory,
  RotationHistory,
  LogEntry,
  Settings,
  ChartData,
} from '@tls-chaos/shared';

// ── State ──────────────────────────────────────────────────────────────────────
export let activeCertProfile: CertProfile = 'valid';

export function setActiveCertProfile(p: CertProfile) {
  activeCertProfile = p;
}

// ── Certificates ───────────────────────────────────────────────────────────────
export const certificates: Certificate[] = [
  {
    profile: 'valid',
    status: CertificateStatus.VALID,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=TLS Chaos Lab CA, O=Chaos Lab, C=US',
    san: ['gateway.tls-chaos.internal', 'localhost', '127.0.0.1'],
    serialNumber: '0A:1B:2C:3D:4E:5F:6A:7B',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: true,
    chainValid: true,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'expired',
    status: CertificateStatus.EXPIRED,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=TLS Chaos Lab CA, O=Chaos Lab, C=US',
    san: ['gateway.tls-chaos.internal'],
    serialNumber: 'DE:AD:BE:EF:CA:FE:BA:BE',
    notBefore: '2023-01-01T00:00:00Z',
    notAfter: '2024-01-01T00:00:00Z',
    daysUntilExpiry: -500,
    isTrusted: true,
    chainValid: true,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'self-signed',
    status: CertificateStatus.UNKNOWN_CA,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=gateway.tls-chaos.internal',
    san: ['gateway.tls-chaos.internal'],
    serialNumber: 'C0:FF:EE:C0:FF:EE:C0:FF',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: false,
    chainValid: false,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'wrong-host',
    status: CertificateStatus.HOSTNAME_MISMATCH,
    subject: 'CN=wronghost.example.com',
    issuer: 'CN=TLS Chaos Lab CA, O=Chaos Lab, C=US',
    san: ['wronghost.example.com', 'other.example.com'],
    serialNumber: '11:22:33:44:55:66:77:88',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: true,
    chainValid: true,
    hostnameValid: false,
    keyMatchesCert: true,
  },
  {
    profile: 'future',
    status: CertificateStatus.NOT_YET_VALID,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=TLS Chaos Lab CA, O=Chaos Lab, C=US',
    san: ['gateway.tls-chaos.internal'],
    serialNumber: 'FF:00:FF:00:FF:00:FF:00',
    notBefore: '2027-06-01T00:00:00Z',
    notAfter: '2028-06-01T00:00:00Z',
    daysUntilExpiry: 1108,
    isTrusted: true,
    chainValid: true,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'broken-chain',
    status: CertificateStatus.BROKEN_CHAIN,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=Intermediate CA (missing)',
    san: ['gateway.tls-chaos.internal'],
    serialNumber: 'AB:CD:EF:AB:CD:EF:AB:CD',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: false,
    chainValid: false,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'key-mismatch',
    status: CertificateStatus.KEY_MISMATCH,
    subject: 'CN=gateway.tls-chaos.internal',
    issuer: 'CN=TLS Chaos Lab CA, O=Chaos Lab, C=US',
    san: ['gateway.tls-chaos.internal'],
    serialNumber: '99:88:77:66:55:44:33:22',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: true,
    chainValid: true,
    hostnameValid: true,
    keyMatchesCert: false,
  },
  {
    profile: 'mtls-client-valid',
    status: CertificateStatus.VALID,
    subject: 'CN=client.tls-chaos.internal, OU=clients',
    issuer: 'CN=TLS Chaos Lab Client CA, O=Chaos Lab, C=US',
    san: ['client.tls-chaos.internal'],
    serialNumber: '0C:LL:1E:N:T:00:00:01',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: true,
    chainValid: true,
    hostnameValid: true,
    keyMatchesCert: true,
  },
  {
    profile: 'mtls-client-invalid',
    status: CertificateStatus.MTLS_FAILED,
    subject: 'CN=badclient.tls-chaos.internal',
    issuer: 'CN=Unknown Client CA',
    san: ['badclient.tls-chaos.internal'],
    serialNumber: 'BA:DC:LL:1E:NT:00:00:01',
    notBefore: '2025-01-01T00:00:00Z',
    notAfter: '2026-12-31T23:59:59Z',
    daysUntilExpiry: 591,
    isTrusted: false,
    chainValid: false,
    hostnameValid: false,
    keyMatchesCert: true,
  },
];

// ── Test Cases ─────────────────────────────────────────────────────────────────
export const testCases: TestCase[] = [
  // Positive tests (8)
  {
    id: 'tc-pos-001',
    name: 'Valid TLS handshake succeeds',
    type: 'positive',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'HTTP 200 OK with valid TLS session established',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-002',
    name: 'HTTPS GET /healthz returns 200',
    type: 'positive',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'HTTP 200 with body {"status":"ok"}',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-003',
    name: 'Gateway proxies to service over TLS',
    type: 'positive',
    path: 'gateway-service',
    activeCertProfile: 'valid',
    expectedResult: 'Service response received with TLS metadata header',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-004',
    name: 'Service connects to MinIO over TLS',
    type: 'positive',
    path: 'service-minio',
    activeCertProfile: 'valid',
    expectedResult: 'S3 ListBuckets returns HTTP 200',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-005',
    name: 'mTLS client cert accepted',
    type: 'positive',
    path: 'mtls',
    activeCertProfile: 'mtls-client-valid',
    expectedResult: 'HTTP 200 with X-Client-Cert-CN header present',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-006',
    name: 'Certificate rotation completes successfully',
    type: 'positive',
    path: 'rotation',
    activeCertProfile: 'valid',
    expectedResult: 'Rotation status: success, new cert loaded within 5s',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-007',
    name: 'TLS 1.3 negotiation succeeds',
    type: 'positive',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'TLS version 1.3 confirmed in session info',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },
  {
    id: 'tc-pos-008',
    name: 'HSTS header present in response',
    type: 'positive',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'Strict-Transport-Security header with max-age>=31536000',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: null,
  },

  // Negative tests (15)
  {
    id: 'tc-neg-001',
    name: 'Expired cert causes TLS handshake failure',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'expired',
    expectedResult: 'TLS error: certificate has expired (x509)',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
  },
  {
    id: 'tc-neg-002',
    name: 'Self-signed cert rejected by client',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'self-signed',
    expectedResult: 'TLS error: unknown certificate authority',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_UNKNOWN_CA,
  },
  {
    id: 'tc-neg-003',
    name: 'Wrong hostname triggers cert mismatch',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'wrong-host',
    expectedResult: 'TLS error: certificate hostname mismatch',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_HOSTNAME_MISMATCH,
  },
  {
    id: 'tc-neg-004',
    name: 'Future cert not yet valid',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'future',
    expectedResult: 'TLS error: certificate is not yet valid',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CERT_NOT_YET_VALID,
  },
  {
    id: 'tc-neg-005',
    name: 'Broken chain causes verification failure',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'broken-chain',
    expectedResult: 'TLS error: certificate chain incomplete',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CHAIN_INVALID,
  },
  {
    id: 'tc-neg-006',
    name: 'Key mismatch causes TLS failure',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'key-mismatch',
    expectedResult: 'TLS error: private key does not match certificate',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_KEY_CERT_MISMATCH,
  },
  {
    id: 'tc-neg-007',
    name: 'mTLS with invalid client cert rejected',
    type: 'negative',
    path: 'mtls',
    activeCertProfile: 'mtls-client-invalid',
    expectedResult: 'HTTP 400 bad_certificate or connection refused',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CLIENT_CERT_INVALID,
  },
  {
    id: 'tc-neg-008',
    name: 'mTLS without client cert causes 400',
    type: 'negative',
    path: 'mtls',
    activeCertProfile: 'valid',
    expectedResult: 'HTTP 400 certificate required',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CLIENT_CERT_MISSING,
  },
  {
    id: 'tc-neg-009',
    name: 'Gateway upstream TLS failure causes 502',
    type: 'negative',
    path: 'gateway-service',
    activeCertProfile: 'expired',
    expectedResult: 'HTTP 502 from gateway due to upstream TLS error',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.UPSTREAM_TLS_HANDSHAKE_FAILED,
  },
  {
    id: 'tc-neg-010',
    name: 'Service to MinIO with expired cert returns 503',
    type: 'negative',
    path: 'service-minio',
    activeCertProfile: 'expired',
    expectedResult: 'HTTP 503 service unavailable from MinIO connection',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
  },
  {
    id: 'tc-neg-011',
    name: 'TLS 1.0 negotiation rejected',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'Connection closed: TLS version not supported',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_VERSION_UNSUPPORTED,
  },
  {
    id: 'tc-neg-012',
    name: 'RC4 cipher suite rejected',
    type: 'negative',
    path: 'client-gateway',
    activeCertProfile: 'valid',
    expectedResult: 'Handshake failure: no common cipher suite',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CIPHER_MISMATCH,
  },
  {
    id: 'tc-neg-013',
    name: 'Rotation to key-mismatch profile fails',
    type: 'negative',
    path: 'rotation',
    activeCertProfile: 'key-mismatch',
    expectedResult: 'Rotation status: failed, previous cert preserved',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_KEY_CERT_MISMATCH,
  },
  {
    id: 'tc-neg-014',
    name: 'Self-signed cert causes upstream 502',
    type: 'negative',
    path: 'gateway-service',
    activeCertProfile: 'self-signed',
    expectedResult: 'HTTP 502 gateway cannot verify upstream self-signed cert',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_UNKNOWN_CA,
  },
  {
    id: 'tc-neg-015',
    name: 'Broken chain on MinIO path causes 503',
    type: 'negative',
    path: 'service-minio',
    activeCertProfile: 'broken-chain',
    expectedResult: 'HTTP 503 MinIO TLS chain verification failed',
    actualResult: '',
    status: TestStatus.NOT_RUN,
    lastRunTime: null,
    duration: null,
    errorCategory: ErrorCategory.TLS_CHAIN_INVALID,
  },
];

// ── Rotation History ───────────────────────────────────────────────────────────
export const rotationHistory: RotationHistory[] = [
  {
    id: 'rot-001',
    timestamp: '2026-05-19T08:00:00Z',
    fromProfile: 'expired',
    toProfile: 'valid',
    status: 'success',
    triggeredBy: 'admin@chaos-lab',
    message: 'Restored valid certificate after expiry chaos test',
  },
  {
    id: 'rot-002',
    timestamp: '2026-05-18T14:30:00Z',
    fromProfile: 'valid',
    toProfile: 'expired',
    status: 'success',
    triggeredBy: 'ci-pipeline',
    message: 'Injected expired cert for chaos scenario tc-neg-001',
  },
  {
    id: 'rot-003',
    timestamp: '2026-05-17T11:15:00Z',
    fromProfile: 'self-signed',
    toProfile: 'valid',
    status: 'success',
    triggeredBy: 'admin@chaos-lab',
    message: 'Restored valid cert after unknown-CA test',
  },
  {
    id: 'rot-004',
    timestamp: '2026-05-16T16:45:00Z',
    fromProfile: 'valid',
    toProfile: 'key-mismatch',
    status: 'failed',
    triggeredBy: 'ci-pipeline',
    message: 'Rotation rejected: private key does not match certificate public key',
  },
  {
    id: 'rot-005',
    timestamp: '2026-05-15T09:20:00Z',
    fromProfile: 'valid',
    toProfile: 'wrong-host',
    status: 'success',
    triggeredBy: 'admin@chaos-lab',
    message: 'Injected wrong-hostname cert for hostname mismatch test',
  },
  {
    id: 'rot-006',
    timestamp: '2026-05-14T13:00:00Z',
    fromProfile: 'wrong-host',
    toProfile: 'valid',
    status: 'success',
    triggeredBy: 'admin@chaos-lab',
    message: 'Hostname mismatch test completed, restored valid cert',
  },
  {
    id: 'rot-007',
    timestamp: '2026-05-13T10:05:00Z',
    fromProfile: 'valid',
    toProfile: 'broken-chain',
    status: 'success',
    triggeredBy: 'ci-pipeline',
    message: 'Injected broken-chain cert for chain validation chaos test',
  },
];

// ── Log Entries ────────────────────────────────────────────────────────────────
export const logEntries: LogEntry[] = [
  {
    id: 'log-001',
    timestamp: '2026-05-19T08:01:00Z',
    severity: 'info',
    component: 'gateway',
    message: 'TLS certificate loaded successfully: CN=gateway.tls-chaos.internal, expires 2026-12-31',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-002',
    timestamp: '2026-05-19T08:01:05Z',
    severity: 'info',
    component: 'gateway',
    message: 'NGINX reload completed, new certificate active',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-003',
    timestamp: '2026-05-19T08:02:00Z',
    severity: 'info',
    component: 'app',
    message: 'Health check passed: all upstream TLS connections verified',
    errorCategory: null,
    testCaseId: 'tc-pos-001',
    certProfile: 'valid',
  },
  {
    id: 'log-004',
    timestamp: '2026-05-18T14:30:10Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: x509: certificate has expired or is not yet valid: current time 2026-05-18T14:30:10Z is after 2024-01-01T00:00:00Z',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-001',
    certProfile: 'expired',
  },
  {
    id: 'log-005',
    timestamp: '2026-05-18T14:30:11Z',
    severity: 'error',
    component: 'gateway',
    message: 'Client connection rejected: SSL_ERROR_RX_RECORD_TOO_LONG - certificate expired',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-001',
    certProfile: 'expired',
  },
  {
    id: 'log-006',
    timestamp: '2026-05-18T14:30:12Z',
    severity: 'warn',
    component: 'app',
    message: 'Upstream gateway returned non-2xx: HTTP 503, retrying in 5s',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-001',
    certProfile: 'expired',
  },
  {
    id: 'log-007',
    timestamp: '2026-05-17T11:10:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: x509: certificate signed by unknown authority',
    errorCategory: ErrorCategory.TLS_UNKNOWN_CA,
    testCaseId: 'tc-neg-002',
    certProfile: 'self-signed',
  },
  {
    id: 'log-008',
    timestamp: '2026-05-17T11:10:01Z',
    severity: 'error',
    component: 'gateway',
    message: 'SSL verify error: depth=0, error=self signed certificate',
    errorCategory: ErrorCategory.TLS_UNKNOWN_CA,
    testCaseId: 'tc-neg-002',
    certProfile: 'self-signed',
  },
  {
    id: 'log-009',
    timestamp: '2026-05-17T11:10:02Z',
    severity: 'warn',
    component: 'service',
    message: 'Failed to establish upstream connection: certificate verification failed',
    errorCategory: ErrorCategory.TLS_UNKNOWN_CA,
    testCaseId: 'tc-neg-002',
    certProfile: 'self-signed',
  },
  {
    id: 'log-010',
    timestamp: '2026-05-16T16:40:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: x509: certificate is valid for wronghost.example.com, not gateway.tls-chaos.internal',
    errorCategory: ErrorCategory.TLS_HOSTNAME_MISMATCH,
    testCaseId: 'tc-neg-003',
    certProfile: 'wrong-host',
  },
  {
    id: 'log-011',
    timestamp: '2026-05-16T16:45:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'Certificate rotation failed: tls: private key does not match public key',
    errorCategory: ErrorCategory.TLS_KEY_CERT_MISMATCH,
    testCaseId: 'tc-neg-013',
    certProfile: 'key-mismatch',
  },
  {
    id: 'log-012',
    timestamp: '2026-05-16T16:45:01Z',
    severity: 'warn',
    component: 'gateway',
    message: 'Rolling back to previous certificate profile: valid',
    errorCategory: null,
    testCaseId: 'tc-neg-013',
    certProfile: 'key-mismatch',
  },
  {
    id: 'log-013',
    timestamp: '2026-05-15T09:20:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: x509: certificate is not yet valid: current time is before 2027-06-01T00:00:00Z',
    errorCategory: ErrorCategory.TLS_CERT_NOT_YET_VALID,
    testCaseId: 'tc-neg-004',
    certProfile: 'future',
  },
  {
    id: 'log-014',
    timestamp: '2026-05-15T09:21:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: certificate chain incomplete - intermediate CA not found',
    errorCategory: ErrorCategory.TLS_CHAIN_INVALID,
    testCaseId: 'tc-neg-005',
    certProfile: 'broken-chain',
  },
  {
    id: 'log-015',
    timestamp: '2026-05-15T09:22:00Z',
    severity: 'error',
    component: 'service',
    message: 'mTLS authentication failed: client certificate presented but not trusted by CA',
    errorCategory: ErrorCategory.TLS_CLIENT_CERT_INVALID,
    testCaseId: 'tc-neg-007',
    certProfile: 'mtls-client-invalid',
  },
  {
    id: 'log-016',
    timestamp: '2026-05-15T09:23:00Z',
    severity: 'error',
    component: 'service',
    message: 'mTLS: no client certificate presented, rejecting connection',
    errorCategory: ErrorCategory.TLS_CLIENT_CERT_MISSING,
    testCaseId: 'tc-neg-008',
    certProfile: 'valid',
  },
  {
    id: 'log-017',
    timestamp: '2026-05-15T09:24:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'Upstream TLS handshake failed: connection to service:8443 refused after TLS error',
    errorCategory: ErrorCategory.UPSTREAM_TLS_HANDSHAKE_FAILED,
    testCaseId: 'tc-neg-009',
    certProfile: 'expired',
  },
  {
    id: 'log-018',
    timestamp: '2026-05-15T09:24:01Z',
    severity: 'error',
    component: 'gateway',
    message: 'Responding 502 Bad Gateway: upstream handshake failure',
    errorCategory: ErrorCategory.UPSTREAM_TLS_HANDSHAKE_FAILED,
    testCaseId: 'tc-neg-009',
    certProfile: 'expired',
  },
  {
    id: 'log-019',
    timestamp: '2026-05-15T09:25:00Z',
    severity: 'error',
    component: 'minio',
    message: 'TLS connection from service rejected: certificate expired',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-010',
    certProfile: 'expired',
  },
  {
    id: 'log-020',
    timestamp: '2026-05-15T09:25:01Z',
    severity: 'error',
    component: 'service',
    message: 'MinIO PUT failed: dial tcp minio:9000: tls: certificate has expired',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-010',
    certProfile: 'expired',
  },
  {
    id: 'log-021',
    timestamp: '2026-05-15T09:26:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS version negotiation failed: client offered TLSv1.0, minimum required is TLSv1.2',
    errorCategory: ErrorCategory.TLS_VERSION_UNSUPPORTED,
    testCaseId: 'tc-neg-011',
    certProfile: 'valid',
  },
  {
    id: 'log-022',
    timestamp: '2026-05-15T09:27:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS cipher suite negotiation failed: no shared cipher between client and server',
    errorCategory: ErrorCategory.TLS_CIPHER_MISMATCH,
    testCaseId: 'tc-neg-012',
    certProfile: 'valid',
  },
  {
    id: 'log-023',
    timestamp: '2026-05-19T07:00:00Z',
    severity: 'debug',
    component: 'gateway',
    message: 'OCSP stapling response cached, next refresh in 3600s',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-024',
    timestamp: '2026-05-19T07:30:00Z',
    severity: 'debug',
    component: 'service',
    message: 'TLS session cache hit for connection to minio:9000',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-025',
    timestamp: '2026-05-19T07:45:00Z',
    severity: 'info',
    component: 'app',
    message: 'Certificate expiry check: valid cert expires in 591 days - no action required',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-026',
    timestamp: '2026-05-19T06:00:00Z',
    severity: 'info',
    component: 'minio',
    message: 'MinIO started with TLS enabled, listening on :9000',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-027',
    timestamp: '2026-05-19T06:01:00Z',
    severity: 'info',
    component: 'service',
    message: 'Service started, establishing TLS connection to MinIO...',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-028',
    timestamp: '2026-05-19T06:01:05Z',
    severity: 'info',
    component: 'service',
    message: 'MinIO TLS handshake successful, session established',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-029',
    timestamp: '2026-05-19T06:02:00Z',
    severity: 'info',
    component: 'gateway',
    message: 'Gateway started with TLS termination on :443',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-030',
    timestamp: '2026-05-19T06:03:00Z',
    severity: 'debug',
    component: 'gateway',
    message: 'TLS session tickets rotated, new key material generated',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-031',
    timestamp: '2026-05-18T20:00:00Z',
    severity: 'warn',
    component: 'app',
    message: 'Certificate expiry alert: cert expires in 12 days (threshold: 30 days)',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'expired',
  },
  {
    id: 'log-032',
    timestamp: '2026-05-18T20:01:00Z',
    severity: 'warn',
    component: 'gateway',
    message: 'Certificate nearing expiry: 12 days remaining, please renew',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'expired',
  },
  {
    id: 'log-033',
    timestamp: '2026-05-18T12:00:00Z',
    severity: 'info',
    component: 'app',
    message: 'Chaos test suite started: running 23 test cases against active profile "valid"',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-034',
    timestamp: '2026-05-18T12:01:00Z',
    severity: 'info',
    component: 'app',
    message: 'Test tc-pos-001 PASSED: Valid TLS handshake succeeds (234ms)',
    errorCategory: null,
    testCaseId: 'tc-pos-001',
    certProfile: 'valid',
  },
  {
    id: 'log-035',
    timestamp: '2026-05-18T12:01:30Z',
    severity: 'info',
    component: 'app',
    message: 'Test tc-pos-002 PASSED: HTTPS GET /healthz returns 200 (187ms)',
    errorCategory: null,
    testCaseId: 'tc-pos-002',
    certProfile: 'valid',
  },
  {
    id: 'log-036',
    timestamp: '2026-05-18T12:02:00Z',
    severity: 'info',
    component: 'app',
    message: 'Test tc-pos-003 PASSED: Gateway proxies to service over TLS (412ms)',
    errorCategory: null,
    testCaseId: 'tc-pos-003',
    certProfile: 'valid',
  },
  {
    id: 'log-037',
    timestamp: '2026-05-18T12:02:30Z',
    severity: 'error',
    component: 'app',
    message: 'Test tc-neg-001 FAILED: Expected expired cert error but got HTTP 200 (cert may have been swapped)',
    errorCategory: ErrorCategory.TLS_CERT_EXPIRED,
    testCaseId: 'tc-neg-001',
    certProfile: 'valid',
  },
  {
    id: 'log-038',
    timestamp: '2026-05-18T12:03:00Z',
    severity: 'info',
    component: 'gateway',
    message: 'TLS handshake completed: client=10.0.0.5, cipher=TLS_AES_256_GCM_SHA384, version=TLSv1.3',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-039',
    timestamp: '2026-05-18T12:04:00Z',
    severity: 'debug',
    component: 'service',
    message: 'Connection pool to minio:9000: active=3, idle=7, pending=0',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-040',
    timestamp: '2026-05-18T12:05:00Z',
    severity: 'info',
    component: 'minio',
    message: 'PUT /bucket/chaos-test-object 200 OK (1.2MB in 234ms)',
    errorCategory: null,
    testCaseId: 'tc-pos-004',
    certProfile: 'valid',
  },
  {
    id: 'log-041',
    timestamp: '2026-05-18T12:06:00Z',
    severity: 'info',
    component: 'app',
    message: 'mTLS test: client cert CN=client.tls-chaos.internal accepted, X-Client-Cert-CN header injected',
    errorCategory: null,
    testCaseId: 'tc-pos-005',
    certProfile: 'mtls-client-valid',
  },
  {
    id: 'log-042',
    timestamp: '2026-05-18T12:07:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'mTLS verification failed: certificate signed by unknown authority (CN=Unknown Client CA)',
    errorCategory: ErrorCategory.TLS_CLIENT_CERT_INVALID,
    testCaseId: 'tc-neg-007',
    certProfile: 'mtls-client-invalid',
  },
  {
    id: 'log-043',
    timestamp: '2026-05-18T12:08:00Z',
    severity: 'error',
    component: 'gateway',
    message: 'TLS handshake failed: broken chain - intermediate CA missing from certificate bundle',
    errorCategory: ErrorCategory.TLS_CHAIN_INVALID,
    testCaseId: 'tc-neg-005',
    certProfile: 'broken-chain',
  },
  {
    id: 'log-044',
    timestamp: '2026-05-18T12:09:00Z',
    severity: 'warn',
    component: 'service',
    message: 'Upstream connection to gateway returned 502, checking TLS configuration',
    errorCategory: ErrorCategory.UPSTREAM_TLS_HANDSHAKE_FAILED,
    testCaseId: 'tc-neg-009',
    certProfile: 'expired',
  },
  {
    id: 'log-045',
    timestamp: '2026-05-18T12:10:00Z',
    severity: 'info',
    component: 'app',
    message: 'Test suite completed: 16 passed, 7 failed. Generating chaos report...',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-046',
    timestamp: '2026-05-19T05:00:00Z',
    severity: 'debug',
    component: 'gateway',
    message: 'Certificate OCSP response: good (this update: 2026-05-19T04:00:00Z, next update: 2026-05-20T04:00:00Z)',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-047',
    timestamp: '2026-05-19T04:00:00Z',
    severity: 'debug',
    component: 'gateway',
    message: 'TLS ticket key rotation completed, old keys expired',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-048',
    timestamp: '2026-05-19T03:00:00Z',
    severity: 'info',
    component: 'app',
    message: 'Scheduled cert expiry scan: all profiles checked, 1 expired, 1 future, 7 operational',
    errorCategory: null,
    testCaseId: null,
    certProfile: null,
  },
  {
    id: 'log-049',
    timestamp: '2026-05-19T02:00:00Z',
    severity: 'debug',
    component: 'service',
    message: 'TLS renegotiation disabled (CVE-2009-3555 mitigation active)',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-050',
    timestamp: '2026-05-19T01:00:00Z',
    severity: 'info',
    component: 'minio',
    message: 'TLS client auth (mTLS) enabled on port 9000, CA bundle loaded with 2 trusted CAs',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-051',
    timestamp: '2026-05-19T00:30:00Z',
    severity: 'warn',
    component: 'gateway',
    message: 'TLS session cache memory pressure: evicting 1000 oldest sessions',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-052',
    timestamp: '2026-05-18T23:00:00Z',
    severity: 'info',
    component: 'app',
    message: 'Cert-manager watch: no certificate renewal events in last hour',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
  {
    id: 'log-053',
    timestamp: '2026-05-18T22:00:00Z',
    severity: 'debug',
    component: 'gateway',
    message: 'SNI routing: request for gateway.tls-chaos.internal matched vhost[0]',
    errorCategory: null,
    testCaseId: null,
    certProfile: 'valid',
  },
];

// ── Settings ───────────────────────────────────────────────────────────────────
export let settings: Settings = {
  environmentName: 'TLS Chaos Lab (Dev)',
  kubernetesNamespace: 'tls-chaos',
  gatewayHostname: 'gateway.tls-chaos.internal',
  gatewayPort: 443,
  caBundlePath: '/etc/ssl/certs/tls-chaos-ca-bundle.pem',
  prometheusUrl: 'http://prometheus.monitoring.svc.cluster.local:9090',
  lokiUrl: 'http://loki.monitoring.svc.cluster.local:3100',
  enableMtls: true,
  expiryAlertThresholdDays: 30,
};

export function updateSettings(partial: Partial<Settings>) {
  settings = { ...settings, ...partial };
}

// ── Chart Data ─────────────────────────────────────────────────────────────────
function hoursAgo(h: number): string {
  const d = new Date('2026-05-19T09:00:00Z');
  d.setHours(d.getHours() - h);
  return d.toISOString();
}

export function generateChartData(): ChartData {
  const tlsHandshakeErrors = Array.from({ length: 25 }, (_, i) => ({
    time: hoursAgo(24 - i),
    value: [0, 0, 0, 0, 0, 0, 12, 34, 45, 38, 22, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8, 3, 0, 0, 0][i] ?? 0,
  }));

  const gateway4xx5xx = Array.from({ length: 25 }, (_, i) => ({
    time: hoursAgo(24 - i),
    value: [2, 1, 0, 1, 2, 1, 28, 52, 67, 59, 31, 4, 2, 1, 3, 2, 1, 0, 2, 14, 19, 8, 2, 1, 0][i] ?? 0,
  }));

  const testPassFail = Array.from({ length: 25 }, (_, i) => ({
    time: hoursAgo(24 - i),
    pass: [0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 8][i] ?? 0,
    fail: [0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0][i] ?? 0,
  }));

  const certExpiryTimeline: ChartData['certExpiryTimeline'] = [
    { profile: 'valid', daysUntilExpiry: 591 },
    { profile: 'self-signed', daysUntilExpiry: 591 },
    { profile: 'wrong-host', daysUntilExpiry: 591 },
    { profile: 'broken-chain', daysUntilExpiry: 591 },
    { profile: 'key-mismatch', daysUntilExpiry: 591 },
    { profile: 'mtls-client-valid', daysUntilExpiry: 591 },
    { profile: 'mtls-client-invalid', daysUntilExpiry: 591 },
    { profile: 'future', daysUntilExpiry: 1108 },
    { profile: 'expired', daysUntilExpiry: -500 },
  ];

  return { tlsHandshakeErrors, gateway4xx5xx, testPassFail, certExpiryTimeline };
}
